name: Build AppImage

on:
  release:
    types: [published]

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install development files
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev gettext
      - name: Build project
        run: bash build.sh

      - name: Build AppImage
        run: bash build-appimage.sh

      - name: Upload Looksyk-x86_64.AppImage
        run: gh release upload "$GITHUB_REF_NAME" BudgetButlerWeb-x86_64.AppImage --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
