name: Check Version Consistency
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
    base: [ stable ]
    paths-ignore:
      - '**.md'
jobs:
  check-versions:
    name: check versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cd deploy/version-checker && cargo run -- --version-path ../../.version.check.json --changelog-path ../../docs/changelog.md
        working-directory: ./