name: Check Version Consistency
on:
  pull_request:
    branches: [ stable ]
    types: [ opened, synchronize, reopened ]
    base: [ stable ]
    paths-ignore:
      - '**.md'
jobs:
  backend-test:
    name: check versions
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'main' && github.event.pull_request.base.ref == 'stable'
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cd deploy/version-checker && cargo run -- --version-path ../../.version.check.json --changelog-path ../../docs/changelog.md
        working-directory: ./